- name: server
  hosts: all
  become: True
  pre_tasks:
    - apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
  roles:
    - role: webservers
      project_name: concourse
