---
dependencies:
  - role: geerlingguy.pip
    pip_package: python3-pip
    pip_executable: pip3
    pip_install_packages:
      - name: docker
      - name: docker-compose
      - name: jsondiff
  - role: geerlingguy.docker
